name: Suggest Content
description: Suggest content to be added to the archive.
labels: ["proposal"]
body:
  - type: markdown
    attributes:
      value: >
        Thanks for your interest in Ace Archive! This is a form for suggesting
        content to be added to the archive. Alternatively, if you want to add
        content to the archive yourself, you can fill out [this more
        comprehensive form](https://acearchive.lgbt/submit/) instead.
  - type: textarea
    id: context
    attributes:
      label: "Context and significance"
      description: >
        What is the content you're suggesting be added to the archive? Why is it
        significant to the queer community? Why should it be included in the
        archive?
    validations:
      required: true
  - type: textarea
    id: sources
    attributes:
      label: "Sources"
      description: >
        Where can we find this content? Please provide URLs. In the case of
        published works, we prefer more authoritative sources like journal
        databases, libraries, and archives like the Internet Archive, but this
        can also be as simple as a link to a forum thread or a blog post. If the
        content isn't accessible or is written in a language other than English,
        consider whether a transcript or a translation are available. If the
        content isn't available on the web anymore, [Wayback
        Machine](https://web.archive.org/) links are fine!
    validations:
      required: true
  - type: textarea
    id: warnings
    attributes:
      label: "Content warnings"
      description: >
        Are there any content warnings which should be attached to this content?
  - type: textarea
    id: extra
    attributes:
      label: "Anything else?"
      description: >
        Is there anything else you want to mention?
