name: "Submit Artifacts"

on:
  workflow_call:
    inputs:
      upload:
        required: true
        type: boolean

jobs:
  submit:
    name: "Submit Artifacts"
    runs-on: ubuntu-latest
    outputs:
      artifacts: ${{ steps.submit.outputs.artifacts }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Submit"
        id: submit
        uses: acearchive/artifact-submit-action@main
        with:
          upload: ${{ inputs.upload }}
          path: "submissions/"
          base_url: "https://files.acearchive.lgbt/artifacts"
          s3_endpoint: ${{ secrets.ARTIFACTS_R2_ENDPOINT }}
          s3_bucket: ${{ secrets.ARTIFACTS_R2_BUCKET }}
          s3_prefix: "artifacts/"
          s3_region: "auto"
          s3_access_key_id: ${{ secrets.R2_ACCESS_KEY_ID }}
          s3_secret_access_key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          cloudflare_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          kv_namespace_id: ${{ secrets.ARTIFACTS_KV_NAMESPACE_ID }}
  generate:
    name: "Generate Hugo Files"
    needs: submit
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          repository: "acearchive/hugo-artifacts"
      - name: "Generate Files"
        uses: "acearchive/hugo-artifact-action@main"
        with:
          path: "artifacts/"
          artifacts: ${{ needs.submit.outputs.artifacts }}
      - name: "Commit Changes"
        uses: "stefanzweifel/git-auto-commit-action@v4"
        with:
          commit_message: "Apply automatic changes"
          file_pattern: "artifacts/*.md"
