name: "Validate Submissions"

on:
  workflow_dispatch:
    inputs:
      base_ref:
        description: "The base ref to determine which artifacts to upload"
        required: true
        default: "HEAD~1"
        type: string
  pull_request:
    paths: ["submissions/*.json"]

jobs:
  validate:
    name: "Validate Submissions"
    uses: ./.github/workflows/submit.yaml
    with:
      mode: "validate"
      # We default to HEAD~1 for pull_request events.
      base_ref: ${{ github.event.inputs.base_ref || "HEAD~1" }}
    secrets: inherit
