name: "Validate Submissions"

on:
  workflow_dispatch:
  pull_request:
    paths: ["submissions/*.json"]

jobs:
  validate:
    name: "Validate Submissions"
    uses: ./.github/workflows/submit.yaml
    with:
      upload: false
    secrets: inherit
